
CREATE TABLE "Product" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(1000) NOT NULL,
  "price" numeric(10,2) NOT NULL,
  "metric_id" integer NOT NULL,
  "supplier_id" integer NOT NULL
);

CREATE TABLE "PriceHistory" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" integer NOT NULL,
  "old_price" decimal(10,2) NOT NULL,
  "new_price" decimal(10,2) NOT NULL,
  "changed_at" timestamp NOT NULL,
  "changed_by" varchar(100)
);

CREATE TABLE "AmountIn" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "metric" varchar(10) NOT NULL
);

CREATE TABLE "DeliveryItems" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" integer NOT NULL,
  "delivery_id" integer NOT NULL,
  "amount_of_product" real NOT NULL,
  "price_paid" decimal(10,2) NOT NULL
);

CREATE TABLE "Suppliers" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(300) NOT NULL,
  "inn" varchar(12) UNIQUE NOT NULL,
  "country" varchar(100) NOT NULL,
  "city" varchar(100) NOT NULL,
  "street" varchar(150) NOT NULL,
  "phone" varchar(20) UNIQUE NOT NULL,
  "email" varchar(100)
);

CREATE TABLE "DeliveryItself" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "customer_id" integer NOT NULL,
  "contract_date" date NOT NULL,
  "start_date" date NOT NULL,
  "end_date" date NOT NULL,
  "total_amount_of_money" decimal(15,2) NOT NULL,
  "description" text,
  "status" varchar(20) NOT NULL,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp
);

CREATE TABLE "Customer" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(300) NOT NULL,
  "country" varchar(100) NOT NULL,
  "city" varchar(100) NOT NULL,
  "street" varchar(150) NOT NULL,
  "house" varchar(10) NOT NULL,
  "inn" varchar(100) NOT NULL
);

ALTER TABLE "PriceHistory" ADD FOREIGN KEY ("product_id") REFERENCES "Product" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Product" ADD FOREIGN KEY ("metric_id") REFERENCES "AmountIn" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Product" ADD FOREIGN KEY ("supplier_id") REFERENCES "Suppliers" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "DeliveryItems" ADD FOREIGN KEY ("product_id") REFERENCES "Product" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "DeliveryItems" ADD FOREIGN KEY ("delivery_id") REFERENCES "DeliveryItself" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "DeliveryItself" ADD FOREIGN KEY ("customer_id") REFERENCES "Customer" ("id") DEFERRABLE INITIALLY IMMEDIATE;
